name: 'Build & test Back-End'
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    shell: bash
    working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
  unit-tests:
    runs-on: ubuntu-latest
    shell: bash
    working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:unit
